### ISSUE TITLE
Possibly use fakeSMTP for email testing

### ISSUE THREAD

**Issue by Kikketer** [PagerNation/Escalator-API#98]
Locally I'd rather not have to go through the whole process of setting up my Gmail account.
See if something like fakeSMTP would work: http://nilhcem.com/FakeSMTP/

**Comment by jarrydlee** [comment]
This is something we have talked about in the past, but it got put on the back burner while we were building out the rest of the product. 

We should be able to put this on the schedule in the coming weeks.

**Comment by jarrydlee** [comment]
I was mistaken with this, we actually don't need the email account for testing purposes. 

As far as implementing this change, we just need to make the SMTP server more customizable which will allow for fakeSMTP to be used.
